[package]
name = "statusbar"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.10.0"
iced_wgpu = {version="0.10.0",features = ["default_system_font"]}
iced_winit = "0.9.1"
log = "0.4.17"
once_cell = "1.17.1"
serde_json = "1.0.96"
serde = { version = "1.0.163", features = ["derive"] }
xcb = "1.2.1"
tokio = { version = "1.28.1", features = ["full"] }
iced_futures = { version = "0.6.0", features = ["tokio"] }
iced_native = "0.10.3"
sscanf = "0.4.0"
iced_style = "0.8.0"
unicode-segmentation = "1.10.1"
derivative = "2.2.0"
tokio-tungstenite = { version="0.19.0",features = ["native-tls"] }
todoproxy-api = { version = "*", git = "https://github.com/pimpale/todoproxy-api" }
auth-service-api = { version = "*", git = "https://github.com/innexgo/auth-service-api" }
futures-util = "0.3.28"
rand = "0.8.5"
xdg = "2.5.0"
reqwest = { version = "0.11.17", features = ["json"] }
url = "2.3.1"
clap = { version = "4.2.7", features = ["derive"] }
