[package]
name = "statusbar"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.10.0"
iced_wgpu = {version="0.7.0",features = ["default_system_font"]}
iced_winit = "0.6.0"
log = "0.4.17"
once_cell = "1.17.0"
serde_json = "1.0.91"
serde = { version = "1.0.152", features = ["derive"] }
xcb = "1.2.0"
tokio = { version = "1.23.1", features = ["full"] }
iced_futures = { version = "0.5.1", features = ["tokio"] }
iced_native = "0.7.0"
sscanf = "0.4.0"
iced_style = "0.5.1"
unicode-segmentation = "1.10.0"
derivative = "2.2.0"
tokio-tungstenite = "0.18.0"
todoproxy-api = {version = "*", git = "https://github.com/pimpale/todoproxy-api" }
futures-util = "0.3.25"
